### ISSUE TITLE
One 'missing' data point on the graph

### ISSUE THREAD

**Issue by sverx** [maxim-zhao/bmp2tilecompressors#17]
I just realized that beside the two 'uncompressed' data points on the graph it would make sense to have a third one marking the fastest transfer speed it's possible to achieve without needing either the screen to be off or the transfer to happen entirely in vblank.
This is probably a better reference mark for all the decompression routines.

Something like _continuous always safe_ max speed - but maybe in better words :sweat_smile: 

Now, where that point should be is another issue.
We know for the SMS one write every 26 cycles is always safe, but that's not the case for every Game Gears, where this safe value appear to be only every 27 cycles.
Or one could use the _official_ recommended value of 29 cycles.

What do you think about it?

**Comment by maxim-zhao** [comment]
I think many of the existing compressors are "screen off only" (and take multiple frames on substantial data), so it might not be a fair comparison. Maybe a second benchmark with only "screen safe" variants?

The "maximum theoretical" would then be one or more vertical lines on the graph, but likely far enough away from the compressed data points to be somewhat unrelatable.

**Comment by sverx** [comment]
That's a good idea - also because I didn't consider that the existing decompressor could be 'not safe' for screen on.
How do you know which aren't? :thinking:

**Comment by maxim-zhao** [comment]
It's somewhat written in the decompressor code - a few have .defines to enable "screen on" mode but most don't. Most write to VRAM much more slowly than the limit anyway, but aren't protecting against the VRAM state being changed by interrupts. Tweaking them all to be safe for that would slow them down even more...

**Comment by sverx** [comment]
uhm... maybe we could presume that those that don't change interrupt status would run with disabled interrupts? :thinking: 
I mean, it really doesn't make much sense but, how is one supposed to use such sources in a safe way?

**Comment by maxim-zhao** [comment]
For the general case, you disable interrupts/turn off the screen while loading assets. For the alternate case where you want to do it with the screen on - but maybe blocking your game loop for a few frames, if it takes a long time - then the code needs to add necessary delays, and maybe make every read or write surrounded by di/set address/do operation/ei, and never make use of the VDP being stateful.

**Comment by maxim-zhao** [comment]
For reference - 27 cycles per byte is 69.1 tiles per frame. That's right in the middle of the hidden area of the graph, much faster than the fastest compressor (even when not in "speed safe" mode or "interrupt safe" mode) and 60% of the "top speed".

I think it would mess the graph up too much to add this on. The existing "uncompressed" points capture the information that compression is way slower than uncompressed, plus they nicely fit in a gap under the legend...
