### ISSUE TITLE
suboptimal output with compress_plane() in Phantasy Star compression (pscompr)

### ISSUE THREAD

**Issue by sverx** [maxim-zhao/bmp2tilecompressors#2]
I get some "17 FE 82 FD FD 17 FE" which is suboptimal, as the "82 FD FD" could be stored as a single RLE run "02 FD".
In compress_plane() there's a check for runs of at least 3 equal bytes (if it's worth or not to break a non identical run) but in this case you're not breaking anything so you should RLE them.

**Comment by maxim-zhao** [comment]
PR please :) Code says ["normally need a run of 3 to be worth breaking a raw block"](https://github.com/maxim-zhao/bmp2tilecompressors/blob/master/gfxcomp_phantasystar.cpp#L266`) but for optimality I think it needs to detect if the run is indeed between two raw blocks; in all other scenarios, a run of 2 is the break-even point. This would preclude the current forward-only nature of the compressor, but it's not as if we need to preserve that.

One possible algorithm:
- decompose it to a list of runs vs. raw blocks
- merge raw[n]-run[2]-raw[m] triplets into a single raw[n+2+m] block, retaining all other run[2]s
- split oversize blocks (>127)
- emit the bytestream

It would be useful to be able to unit test this sort of thing, e.g. have a corpus of inputs (ideally covering the various edge cases) and confirm that the compression is valid and no worse than the old code. Sounds like a project!

**Comment by sverx** [comment]
"PR" stands for... ? :|
BTW, even with the "forward only" approach, you can see that the two 0xFD bytes are the first two bytes after an RLE run, so they're surely more efficiently coded as a 2 bytes RLE run, whatever may come after that.

**Comment by maxim-zhao** [comment]
PR = pull request, it's Git-ese for "do the work for me". As it happens, I pretty much did it already, but it's mired in a bunch of other stuff I did which needs finishing off (I didn't branch, shame on me).

**Comment by sverx** [comment]
Oh, I see. Well, unfortunately I don't know C++ so I won't even try fixing that myself :|
But you don't have to worry, I was actually just testing alternative compression schemes for my tilemap to see how they fare... but I don't like the "deinterleaved" thing in this one, as it makes writes to VRAM not sequential.

**Comment by maxim-zhao** [comment]
The compression benefits from the deinterleaving, because there's much better byte-wise RLE capacity if you look at the tile bitplanes, and the tile index LSBs and MSBs, separately. You could enhance it to decompress the deinterleaved data in parallel, to get the sequential VRAM writes, but it'd require being able to find the chunks up front.

**Comment by sverx** [comment]
Yeah, I see. I think I'll probably try a different scheme.
Thanks!
