### ISSUE TITLE
it's missing a compressor!

### ISSUE THREAD

**Issue by sverx** [maxim-zhao/bmp2tilecompressors#6]
clickbait title! :rofl: 

I wonder if you want to add the tile compressor plugin and z80 decompressor I just released a few moments ago: https://github.com/sverx/stc0

I expect it to average at about 0.3 compression level and 1000 bytes/frame decompression speed, which will probably mean it's going to be the fastest among all the ones in the list, of course at the price of a very simple compression. We'll see.

**Comment by maxim-zhao** [comment]
Pull request? :) I'd need to add it into the benchmark too.

**Comment by sverx** [comment]
I would provide a PR if I knew what I need to provide... :thinking:

**Comment by maxim-zhao** [comment]
Well, the compressor and decompressor would be combined into this project structure; the advantage is that you get to have your name on the commits. The benchmark part needs a little wrapper to assemble but it's fairly trivial. It's not really possible to bring them in via a submodule as that escapes the project structure, it only really works for compression libraries.

If I just copy/paste the files then they lose the link to your implementations here. I can do that though.

**Comment by maxim-zhao** [comment]
Well, I did it:

![image](https://user-images.githubusercontent.com/7792986/189098418-21e0aa85-9f9c-4bef-9edf-c39efa10aa37.png)
![image](https://user-images.githubusercontent.com/7792986/189100268-025a9047-e8bb-44ce-9ebf-5a8c19bde020.png)

I took the liberty to convert it to CPP and then change a few things around. It is indeed fast but not strong.
